# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Maven DEV deploy

on:
  push:
    branches: [ nic/env/dev ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Cache local Maven repository
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Set output vars
      id: vars
      run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
    - name: Set pom version
      run: |
        mvn versions:set -DnewVersion=1.0-${{ steps.vars.outputs.sha_short }}
        mvn versions:commit
    - name: Update settings.xml
      uses: whelk-io/maven-settings-xml-action@v14
      with:
        repositories: '[{ "id": "github", "url": "https://maven.pkg.github.com/${{ github.repository }}" }]'
        servers: '[{ "id": "github", "username": "${{ github.repository_owner }}", "password": "${{ github.token }}" }]'
    - name: Deploy with Maven
      run: mvn deploy -DaltDeploymentRepository=github::default::https://maven.pkg.github.com/${{ github.repository }} -Dpackaging=jar
